// DIAGNOSTIC performance spec — ONE very large document (e2e/fixtures/large-doc/demo-large.en.md,
// a committed copy of examples/demo-large.en.md).
//
// This spec RECORDS numbers and additionally GATES the Phase-03 outcomes with calibrated
// thresholds (see the ── Thresholds ── block below). It used to be recording-only, because
// writing thresholds with no data would have been a guess (same reasoning as the calibration
// note in switch-perf-gate.e2e.spec.ts). Now that D-E① (mermaid cache + lazy render) and R9
// (image intrinsic size) have landed, the thresholds are calibrated from real runs.
//
// It is registered in BOTH perf projects: `electron-perf` (on-demand diagnostic, prints the
// full report) and `electron-perf-gate` (CI gate, ~12s). Keeping one spec for both roles is
// deliberate — a gate that can drift from the diagnostic it was derived from stops guarding
// anything (the same reasoning as the shared perf-fixture.ts).
//
// It answers, for the three Phase-03 candidates:
//
//   D-E  mermaid caching + viewport lazy-render
//        → firstMermaidMs (how long the first diagram blocks), longTask* (main-thread
//          blocking), mermaidSlots / mermaidRendered.
//   R9   image intrinsic size (zero layout jitter)
//        → cls / clsCount / clsMax (cumulative layout shift while the doc settles).
//          Target after R9 ≈ 0.
//   D-D  block-level incremental render
//        → typeToPreviewMs (input → updated preview on a 3.5k-line doc), blocks.
//
// The fixture (e2e/fixtures/large-doc/demo-large.en.md + assets/*.png) is a committed copy of
// examples/demo-large.en.md (generated by examples/generate-large.mjs, which also emits the
// Chinese sibling examples/demo-large.zh-CN.md) so the run is self-contained. See plan §8 Step 2.
// It holds ~60 mermaid diagrams (20 duplicated on purpose, to expose cache behaviour once D-E
// lands), ~62 local images (appdoc:// → exercises the R9 `documents:image-size` path, including
// the tall `pic-tall.png` that makes the pre-R9 CLS obvious) and ~100 distinct sections
// (block-parse cost).
//
// Run:  npm run e2e:perf            # this spec + the folder-switch diagnostic
//       npx playwright test --project=electron-perf large-doc-perf
//       PERF_UPDATE_BASELINE=1 npx playwright test --project=electron-perf large-doc-perf
//         → also freezes e2e/perf/baselines/large-doc.json for future deltas.
//
// Artifacts: reports/perf/large-doc-<timestamp>.json + large-doc-latest.json
import { test, expect } from '@playwright/test'
import { cpSync } from 'node:fs'
import { join } from 'node:path'
import { launchApp, waitForAppReady, closeApp } from '../helpers/launch'
import { mkTempDir } from '../helpers/temp'
import { installMainProbe, collectMainProbe } from '../helpers/perf'
// `summarizeMainLag` lives beside the folder-switch gate (perf-fixture.ts) and is
// generic main-process lag summarisation — reused as-is so both diagnostics report
// the identical lag semantics.
import { summarizeMainLag } from '../helpers/perf-fixture'
import {
  E2E_FIXTURE_DIR,
  LARGE_DOC_NAME,
  installLoadProbe,
  collectLoadProbe,
  countStructure,
  waitForLocalImages,
  readMainMemory,
  readRendererHeap,
  writeRunRecord,
  maybeWriteBaseline,
  readBaseline,
  baselineDelta,
  type LargeDocMetrics,
} from '../helpers/large-doc-perf'

// ─── Thresholds ─────────────────────────────────────────────────────────────
//
// Calibrated 2026-09-20 from 3 consecutive runs AFTER D-E① (mermaid cache + lazy render) and
// R9 (image intrinsic size) landed — same machine the gate is run on (dev box, Vite dev server
// + Electron, dev build). "before" = the frozen baseline 52682270 (Phase-03 not implemented).
//
//   metric                  run1   run2   run3    before   threshold   headroom
//   firstContentMs           529    492    529      2644     1500       ~2.8x
//   typeToPreviewMs          957    958    993      2535     2000       ~2.0x
//   typeCharToPreviewMs     1241   1235   1232      2756     2000       ~1.6x
//   cls                   0.0045 0.0045 0.0045    0.1719     0.05        ~11x
//   mermaidRendered            4      4      4        60       20         5x
//
// Every threshold sits comfortably above the slowest measured run AND well below the
// pre-Phase-03 value, so a regression to the old behaviour fails loudly while run-to-run
// noise does not. NOTE: this project (electron-perf) is on-demand, NOT the CI gate
// (electron-perf-gate runs switch-perf-gate only), so these thresholds guard hand-run
// regressions; promote to CI only after the numbers are shown stable on the runner.
//
// Override for ad-hoc runs, e.g.
//   PERF_MAX_CLS=0.2 npx playwright test --project=electron-perf large-doc-perf
const MAX_FIRST_CONTENT_MS = Number(process.env.PERF_MAX_FIRST_CONTENT_MS ?? 1500)
const MAX_TYPE_TO_PREVIEW_MS = Number(process.env.PERF_MAX_TYPE_TO_PREVIEW_MS ?? 2000)
const MAX_TYPE_CHAR_MS = Number(process.env.PERF_MAX_TYPE_CHAR_MS ?? 2000)
const MAX_CLS = Number(process.env.PERF_MAX_CLS ?? 0.05)
const MAX_MERMAID_RENDERED = Number(process.env.PERF_MAX_MERMAID_RENDERED ?? 20)

test.describe('large document preview performance (diagnostic)', () => {
  test('open demo-large.en.md, render, type, and record metrics', async () => {
    const handle = await launchApp()
    const { electronApp, page } = handle
    try {
      await installMainProbe(electronApp)
      await waitForAppReady(page)

      // Work on a COPY: typing below must never be able to touch the committed
      // fixture, and relative `assets/*.png` refs keep resolving because the whole
      // examples/ directory (md + assets) is copied together.
      const scratch = mkTempDir('markflow-perf-large-')
      cpSync(E2E_FIXTURE_DIR, scratch, { recursive: true })
      const docPath = join(scratch, LARGE_DOC_NAME)

      const docId = await page.evaluate(
        (f) => window.api.documents.import(f).then((d: any) => d?.id),
        docPath,
      )
      expect(docId, 'demo-large.en.md must import').toBeTruthy()

      // Arm the passive probes BEFORE activation so nothing in the load window is missed.
      await installLoadProbe(page)

      const t0 = Date.now()
      await page.evaluate((id) => {
        const w = window as any
        w.__uiStore.getState().setActiveDocumentId(id)
        w.__queryClient.invalidateQueries({ queryKey: ['documents'] })
      }, docId)

      // ── first content ──
      await expect(page.locator('article.markdown-preview h2').first()).toBeVisible({
        timeout: 60_000,
      })
      const firstContentMs = Date.now() - t0

      // ── first diagram (top-most) ──
      // D-E① renders diagrams LAZILY (IntersectionObserver, rootMargin 200px): this placeholder
      // sits ~4000px down (the two 2000px R9 probe images precede it), so at scrollTop 0 it is
      // far outside the viewport and NEVER bakes on its own. It must be scrolled into view
      // first; the metric then reads activation → scrolled-into-view → first <svg> (the scroll
      // itself is instant, so the value stays dominated by the mermaid compile/render cost).
      await page.locator('[data-mermaid-slot="0"]').scrollIntoViewIfNeeded()
      await expect(page.locator('[data-mermaid-slot="0"] svg')).toBeVisible({ timeout: 120_000 })
      const firstMermaidMs = Date.now() - t0

      // ── local images decoded ──
      await waitForLocalImages(page, 60_000)
      const localImagesMs = Date.now() - t0

      const struct = await countStructure(page)
      expect(struct.localImages, 'fixture must contain local images (R9 path)').toBeGreaterThan(0)
      expect(struct.mermaidSlots, 'fixture must contain diagrams (D-E path)').toBeGreaterThan(0)
      expect(struct.blocks, 'fixture must contain many blocks (D-D path)').toBeGreaterThan(0)
      // Every LOCAL image decoded — a failure here means the fixture is broken, not slow.
      expect(struct.localImagesLoaded).toBe(struct.localImages)

      // ── typing latency on a large document (D-D / D-E cost) ──
      await page.evaluate(() => (window as any).__uiStore.getState().setEditable(true))
      const marker = `PERF_PROBE_${Date.now()}`
      await page.locator('.cm-content').click()
      await page.keyboard.press('Control+End')
      const tType = Date.now()
      await page.keyboard.type(`\n\n${marker}\n`)
      await expect(page.locator('article.markdown-preview p', { hasText: marker })).toHaveCount(1, {
        timeout: 60_000,
      })
      const typeToPreviewMs = Date.now() - tType

      // ── per-keystroke latency: a single insert on the big doc. The dominant cost is
      //    the re-parse + re-render, so this is what the user waits per keystroke. ──
      const charMarker = `KPERF${Date.now()}`
      await page.locator('.cm-content').click()
      await page.keyboard.press('Control+End')
      const tChar = Date.now()
      await page.keyboard.insertText(charMarker)
      await expect(page.locator('article.markdown-preview', { hasText: charMarker })).toBeVisible({
        timeout: 60_000,
      })
      const typeCharToPreviewMs = Date.now() - tChar

      // ── collect the passive probes + main-process lag + memory ──
      const probe = await collectLoadProbe(page)
      const longTasks = probe.longTasks.map((t) => t.dur)
      const main = summarizeMainLag(await collectMainProbe(electronApp))
      const mem = await readMainMemory(electronApp)
      const rendererHeapUsed = await readRendererHeap(page)

      const metrics: LargeDocMetrics = {
        mermaidSlots: struct.mermaidSlots,
        mermaidRendered: struct.mermaidRendered,
        localImages: struct.localImages,
        localImagesLoaded: struct.localImagesLoaded,
        blocks: struct.blocks,
        firstContentMs,
        firstMermaidMs,
        localImagesMs,
        typeToPreviewMs,
        typeCharToPreviewMs,
        cls: probe.cls.reduce((s, v) => s + v, 0),
        clsCount: probe.cls.length,
        clsMax: probe.cls.length ? Math.max(...probe.cls) : 0,
        longTaskCount: longTasks.length,
        longTaskTotalMs: longTasks.reduce((s, v) => s + v, 0),
        longTaskMaxMs: longTasks.length ? Math.max(...longTasks) : 0,
        mainP95Ms: main.p95,
        mainStallMs: main.stallMs,
        mainMaxLagMs: main.maxLag,
        mainHeapUsed: mem.heapUsed,
        mainRss: mem.rss,
        rendererHeapUsed,
      }

      // ── report ──
      console.log('\n\n============ LARGE-DOC PERF REPORT ============')
      console.log(`doc: ${docPath}`)
      console.log(
        `structure: ${metrics.mermaidSlots} mermaid slots (${metrics.mermaidRendered} rendered), ` +
          `${metrics.localImages} local images, ${metrics.blocks} top-level blocks`,
      )
      console.log('--- load (ms from document activation) ---')
      console.log(`  firstContentMs : ${metrics.firstContentMs.toFixed(0)}`)
      console.log(`  firstMermaidMs : ${metrics.firstMermaidMs.toFixed(0)}   [D-E]`)
      console.log(`  localImagesMs  : ${metrics.localImagesMs.toFixed(0)}`)
      console.log('--- input latency ---')
      console.log(`  typeToPreviewMs: ${metrics.typeToPreviewMs.toFixed(0)}   [D-D / D-E]`)
      console.log(
        `  typeCharToPreviewMs: ${metrics.typeCharToPreviewMs.toFixed(0)}   [per-keystroke proxy]`,
      )
      console.log('--- jitter (layout shift) ---')
      console.log(
        `  cls: ${metrics.cls.toFixed(4)}  entries: ${metrics.clsCount}  max: ${metrics.clsMax.toFixed(4)}   [R9]`,
      )
      console.log('--- renderer long tasks (>50ms) ---')
      console.log(
        `  count: ${metrics.longTaskCount}  total: ${metrics.longTaskTotalMs.toFixed(0)}ms  max: ${metrics.longTaskMaxMs.toFixed(0)}ms`,
      )
      console.log('--- main-process event-loop lag ---')
      console.log(
        `  p95: ${metrics.mainP95Ms.toFixed(1)}ms  stallMs: ${metrics.mainStallMs.toFixed(0)}  maxLag: ${metrics.mainMaxLagMs.toFixed(1)}ms`,
      )
      console.log('--- memory ---')
      console.log(
        `  main heapUsed: ${(metrics.mainHeapUsed / 1e6).toFixed(1)}MB  rss: ${(metrics.mainRss / 1e6).toFixed(1)}MB` +
          `  renderer heapUsed: ${metrics.rendererHeapUsed == null ? 'n/a' : (metrics.rendererHeapUsed / 1e6).toFixed(1) + 'MB'}`,
      )

      const baseline = readBaseline()
      if (baseline) {
        console.log(`\n--- vs frozen baseline (commit ${baseline.commit ?? '?'}) ---`)
        for (const line of baselineDelta(metrics, baseline.metrics)) console.log(line)
      } else {
        console.log('\n(no frozen baseline yet — run with PERF_UPDATE_BASELINE=1 to freeze one)')
      }
      console.log('==============================================\n')

      const written = writeRunRecord('large-doc', metrics, docPath)
      const frozen = maybeWriteBaseline('large-doc', metrics)
      console.log('[perf] wrote:', written.join(', '))
      if (frozen) console.log('[perf] froze baseline:', frozen)

      // ── gate (calibration above) ──
      // Asserted AFTER the report + artifacts are persisted, so a failing run still leaves
      // its numbers on disk to diff against. Each threshold targets one Phase-03 candidate:
      console.log('--- thresholds ---')
      console.log(`  firstContentMs      ${firstContentMs}   < ${MAX_FIRST_CONTENT_MS}`)
      console.log(`  typeToPreviewMs     ${typeToPreviewMs}   < ${MAX_TYPE_TO_PREVIEW_MS}`)
      console.log(`  typeCharToPreviewMs ${typeCharToPreviewMs}   < ${MAX_TYPE_CHAR_MS}`)
      console.log(`  cls                 ${metrics.cls.toFixed(4)}   < ${MAX_CLS}`)
      console.log(`  mermaidRendered     ${metrics.mermaidRendered}   < ${MAX_MERMAID_RENDERED}`)

      // D-E: a re-parse must NOT re-bake the whole document, and the first paint must not
      // wait for 60 diagrams.
      expect(
        firstContentMs,
        'activation -> first preview content (D-E eager-bake regression?)',
      ).toBeLessThan(MAX_FIRST_CONTENT_MS)
      expect(
        typeToPreviewMs,
        'input -> updated preview on a 952-block doc (D-E cache regression?)',
      ).toBeLessThan(MAX_TYPE_TO_PREVIEW_MS)
      expect(
        typeCharToPreviewMs,
        'one keystroke -> visible in preview (D-E cache regression?)',
      ).toBeLessThan(MAX_TYPE_CHAR_MS)
      // D-E: lazy render must keep off-screen diagrams UNBAKED. A value near mermaidSlots
      // means every diagram baked again — exactly the cost D-E① removed.
      expect(
        metrics.mermaidRendered,
        'diagrams baked eagerly instead of lazily (D-E lazy-render regression?)',
      ).toBeLessThan(MAX_MERMAID_RENDERED)
      // R9: with intrinsic sizes backfilled before insertion, the tall probe images must no
      // longer push the document down (before: 0.1719).
      expect(metrics.cls, 'cumulative layout shift (R9 image-size regression?)').toBeLessThan(
        MAX_CLS,
      )
    } finally {
      await closeApp(handle)
    }
  })
})
